// Collect data across sites
module.exports = {
  urls: [
    'https://www.google.com',
    'https://google.com/?q=wikipedia',
    'https://www.youtube.com',
    'https://www.youtube.com/watch?v=kFBDn5PiL00',
    'https://www.facebook.com',
    'https://en.wikipedia.org',
    'https://en.wikipedia.org/wiki/YouTube',
    'https://www.nytimes.com/en/',
    'http://www.huffingtonpost.com/',
    'https://github.com/',
    'https://www.instagram.com/',
    'http://yahoo.com',
    'https://www.google.co.in',
    'https://www.amazon.com',
    'http://www.qq.com',
    'https://www.google.co.jp',
    'https://www.outlook.com',
    'https://www.taobao.com',
    'https://medium.com/',
    'https://medium.freecodecamp.com/73-of-programmers-are-web-developers-and-other-insights-from-stack-overflows-massive-2017-survey-89a13b11e370',
    'https://www.duolingo.com/',
    'https://trello.com/',
  ],
}
